---
- name: Install Apache NiFi
  hosts: target_host
  become: true
  vars:
    nifi_version: 1.13.2
    nifi_install_dir: /opt
  tasks:
  - name: Install dependencies
    apt:
      name: openjdk-8-jdk
      update_cache: yes
  - name: Download NiFi binary
    get_url:
      url: https://archive.apache.org/dist/nifi/{{ nifi_version }}/nifi-{{ nifi_version }}-bin.tar.gz
      dest: "{{ nifi_install_dir }}/nifi.tar.gz"
  - name: Extract NiFi binary
    unarchive:
      src: "{{ nifi_install_dir }}/nifi.tar.gz"
      dest: "{{ nifi_install_dir }}"
      remote_src: true
  - name: Start NiFi
    command: "{{ nifi_install_dir }}/nifi-{{ nifi_version }}/bin/nifi.sh start"
